import './node_modules/bootstrap/dist/css/bootstrap.min.css';
import './node_modules/popper.js/dist/popper.min.js';
import './node_modules/bootstrap/dist/js/bootstrap.min.js';
import './node_modules/font-awesome/css/font-awesome.min.css';
import './node_modules/materialize-css/dist/js/materialize.min.js';
import './materialize-css-custom.css';
import './style.css';
import './animations.js';
import './forms.js';